public class PaintCost {

	public static void main(String[] args) {
	/*
	 * This program will calculate the cost to paint a house
	 */
		
	 int houseLengthFeet=20;
	 double inches = 6; 
	 System.out.println(houseLengthFeet + inches/12);
	 
	 int houseWidthFeet=10; 
	 double inches1 = 6;
	 System.out.println(houseWidthFeet + inches/12);
	 
	 int houseHeightFeet=20;
	 double inches2 = 6;
	 System.out.println(houseHeightFeet + inches/12); 
	 
	 int windowLengthFeet=5;
	 double inches3 = 6; 
	 System.out.println(windowLengthFeet + inches/12); 
	 
	 int windowWidthFeet=10;
	 double inches4 = 6;
	 System.out.println(windowsWidthFeet + inches/12); 
	 
	 int doorLengthFeet=10; 
	 double inches5 = 6;
	 System.out.println(doorLengthFeet + inches/12); 
	 
	 int doorWidthFeet=4; 
	 double inches6 = 6; 
	 System.out.println(doorWidthFeet + inches/12);
	 
	 int totalsquareFeet=x; 
	 double inches7 = 6; 
	 System.out.println(x = houseLengthFeet + houseWidthFeet + houseHeightFeet + windowLengthFeet + windowWidthFeet + doorLengthFeet + doorWidthFeet);
	 
	 
	 }

}